version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - redis
      - echo
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:3U9Z7MrsxckmFv224b7m8oFGgpfx0qbrrqJ8ohi0TT0=
      DB_HOST: db
      REDIS_HOST: redis

  redis:
    image: redis:6.2
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: eco_save_local
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  echo:
    image: node:18
    container_name: laravel_echo
    working_dir: /app
    restart: always
    volumes:
      - ./docker/echo:/app
    command: ["npx", "laravel-echo-server", "start"]
    ports:
      - "6001:6001"
    depends_on:
      - redis

volumes:
  mysql_data:
